# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'adicionarFerramenta.ui'
#
# Created by: PyQt5 UI code generator 5.15.0
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_Dialog(object):
    def setupUi(self, Dialog):
        Dialog.setObjectName("Dialog")
        Dialog.resize(320, 240)
        self.verticalLayout = QtWidgets.QVBoxLayout(Dialog)
        self.verticalLayout.setObjectName("verticalLayout")
        self.label = QtWidgets.QLabel(Dialog)
        self.label.setObjectName("label")
        self.verticalLayout.addWidget(self.label)
        self.label_2 = QtWidgets.QLabel(Dialog)
        self.label_2.setObjectName("label_2")
        self.verticalLayout.addWidget(self.label_2)
        self.noFerramentaTE = QtWidgets.QPlainTextEdit(Dialog)
        self.noFerramentaTE.setObjectName("noFerramentaTE")
        self.verticalLayout.addWidget(self.noFerramentaTE)
        self.label_3 = QtWidgets.QLabel(Dialog)
        self.label_3.setObjectName("label_3")
        self.verticalLayout.addWidget(self.label_3)
        self.matriculaSAPTE = QtWidgets.QPlainTextEdit(Dialog)
        self.matriculaSAPTE.setObjectName("matriculaSAPTE")
        self.verticalLayout.addWidget(self.matriculaSAPTE)
        self.label_4 = QtWidgets.QLabel(Dialog)
        self.label_4.setObjectName("label_4")
        self.verticalLayout.addWidget(self.label_4)
        self.validadeCertificadoDE = QtWidgets.QDateEdit(Dialog)
        self.validadeCertificadoDE.setLocale(QtCore.QLocale(QtCore.QLocale.Portuguese, QtCore.QLocale.Brazil))
        self.validadeCertificadoDE.setDateTime(QtCore.QDateTime(QtCore.QDate(2020, 10, 12), QtCore.QTime(0, 0, 0)))
        self.validadeCertificadoDE.setObjectName("validadeCertificadoDE")
        self.verticalLayout.addWidget(self.validadeCertificadoDE)
        self.buttonBox = QtWidgets.QDialogButtonBox(Dialog)
        self.buttonBox.setOrientation(QtCore.Qt.Horizontal)
        self.buttonBox.setStandardButtons(QtWidgets.QDialogButtonBox.Cancel|QtWidgets.QDialogButtonBox.Ok)
        self.buttonBox.setObjectName("buttonBox")
        self.verticalLayout.addWidget(self.buttonBox)

        self.retranslateUi(Dialog)
        self.buttonBox.accepted.connect(Dialog.accept)
        self.buttonBox.rejected.connect(Dialog.reject)
        QtCore.QMetaObject.connectSlotsByName(Dialog)

    def retranslateUi(self, Dialog):
        _translate = QtCore.QCoreApplication.translate
        Dialog.setWindowTitle(_translate("Dialog", "Dialog"))
        self.label.setText(_translate("Dialog", "Adicionar Ferramenta"))
        self.label_2.setText(_translate("Dialog", "Nome da Ferramenta"))
        self.noFerramentaTE.setPlainText(_translate("Dialog", "\n"
""))
        self.noFerramentaTE.setPlaceholderText(_translate("Dialog", "Multímetro Fluke "))
        self.label_3.setText(_translate("Dialog", "Matrícula SAP"))
        self.matriculaSAPTE.setPlaceholderText(_translate("Dialog", "10012581"))
        self.label_4.setText(_translate("Dialog", "Validade do Certificado de Calibração "))
